### ISSUE TITLE
btrfs scrub shows 'aborted' as status when it completes successfully

### ISSUE THREAD

**Issue by josefbacik** [btrfs/btrfs-todo#1] opened 2020-08-25 17:19 UTC
Chris Murphy reported a problem where `btrfs scrub status` reports "aborted" once the scrub finishes successfully.  He had a pastebin, but it's expired, but presumably should be straightforward to reproduce.

**Comment by lorddoskias** [comment] 2020-08-28 13:24
How was it verified that scrub succeeded?  
```

root@ubuntu18:~/xfstests-dev# btrfs scrub start /media/scratch/
scrub started on /media/scratch/, fsid 68738030-40f8-463a-a763-b9afd99daee9 (pid=5820)
root@ubuntu18:~/xfstests-dev# btrfs scrub status /media/scratch/
UUID:             68738030-40f8-463a-a763-b9afd99daee9
Scrub started:    Fri Aug 28 13:23:27 2020
Status:           finished
Duration:         0:00:01
Total to scrub:   538.40MiB
Rate:             538.40MiB/s
Error summary:    no errors found
```

**Comment by josefbacik** [comment] 2020-09-01 14:18
@cmurf do you remember how you reproduced this?

**Comment by cmurf** [comment] 2020-09-01 15:40
No. :facepalm:

It's working with kernel 5.8.5 and progs 5.7 on three bare metal installs. And in qemu-kvm with 5.8.3 and 5.9.rc3.

**Comment by cmurf** [comment] 2021-07-01 21:16
This can be closed (I don't have privileges to do it myself or I would). I can't reproduce it and don't know anyone who has.

**Comment by kdave** [comment] 2021-07-07 14:14
Thanks, closing.

**Closed as completed by kdave** 2021-07-07 14:14 UTC
Labels: bug, kernel, can't reproduce
